# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2022-2025, PyMC Labs
# This file is distributed under the same license as the pymc-marketing
# package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pymc-marketing local\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-07 18:10+0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: es\n"
"Language-Team: es <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: ../source/api/generated/classmethods/pymc_marketing.hsgp_kwargs.HSGPKwargs.__init__.rst:2
#: 886d78a24de2467d98bda480404739e1
msgid "HSGPKwargs.\\_\\_init\\_\\_"
msgstr ""

#: c26f7f39af5b4dd99e9471c788213cf2 of pydantic.main.BaseModel.__init__:2
msgid ""
"Create a new model by parsing and validating input data from keyword "
"arguments."
msgstr ""

#: 970c9f7f262d4b11ac9f964ea5ea910a of pydantic.main.BaseModel.__init__:4
msgid ""
"Raises [`ValidationError`][pydantic_core.ValidationError] if the input "
"data cannot be validated to form a valid model."
msgstr ""

#: fe8653c189bf45c5bf3a90d97b4295dc of pydantic.main.BaseModel.__init__:7
msgid "`self` is explicitly positional-only to allow `self` as a field name."
msgstr ""
